

//login
POST http://127.0.0.1:8080/gdpr-expert-web/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=qaa@mail.ru&password=q




POST http://127.0.0.1:8080/gdpr-expert-web/api/registration HTTP/1.1
Content-Type: application/json

{
  "email": "q@mail.ru",
  "password": "q"
}
