

GET http://127.0.0.1:8080/gdpr-expert-web/home


GET http://127.0.0.1:8080/gdpr-expert-web/api/auth/success
Content-Type: application/json


//login
POST http://127.0.0.1:8080/gdpr-expert-web/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=q@mail.ru&password=q




POST http://127.0.0.1:8080/gdpr-expert-web/logout HTTP/1.1


POST http://127.0.0.1:8080/gdpr-expert-web/api/signin HTTP/1.1

//login
POST http://127.0.0.1:8080/gdpr-expert-web/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=q@mail.ru&password=q




POST http://127.0.0.1:8080/gdpr-expert-web/api/registration HTTP/1.1
Content-Type: application/json

{
  "email": "q124@mail.ru",
  "password": "q"
}

//test
GET https://cdn.animenewsnetwork.com/encyclopedia/api.xml?anime=461341358

// remove employee
DELETE http://127.0.0.1:8080/gdpr-expert-web/api/employee/22 HTTP/1.1

// employees for dep
GET http://127.0.0.1:8080/gdpr-expert-web/api/employee/department/4 HTTP/1.1

// get employee by id
GET http://127.0.0.1:8080/gdpr-expert-web/api/employee/23 HTTP/1.1

// update employee
PUT http://127.0.0.1:8080/gdpr-expert-web/api/employee HTTP/1.1
Content-Type: application/json

{
  "id": 15,
  "personalDataResponsible": false,
  "firstName": "adf",
  "lastName": "",
  "email":"q124@mail.ru33",
  "phoneNumber": "13948319444",
  "address": "str. afdad 3255"
}

//create employee
POST http://127.0.0.1:8080/gdpr-expert-web/api/employee/add HTTP/1.1
Content-Type: application/json

{
  "departmentId": 15,
  "personalDataResponsible": true,
  "firstName": "fname",
  "lastName": "lname",
  "email":"q124@mail.ru",
  "phoneNumber": "139483194",
  "address": "str. afdad 32"
}


GET http://127.0.0.1:8080/gdpr-expert-web/api/organisation/all HTTP/1.1

// departments for org
GET http://127.0.0.1:8080/gdpr-expert-web/api/department/organisation/3 HTTP/1.1


// org info
GET http://127.0.0.1:8080/gdpr-expert-web/api/organisation/info/1 HTTP/1.1


//department by id
GET http://127.0.0.1:8080/gdpr-expert-web/api/department/4 HTTP/1.1

//remove department
DELETE http://127.0.0.1:8080/gdpr-expert-web/api/department/4 HTTP/1.1

DELETE http://127.0.0.1:8080/gdpr-expert-web/api/department/4

//update department
PUT http://127.0.0.1:8080/gdpr-expert-web/api/department HTTP/1.1
Content-Type: application/json

{
  "id": 4,
  "responsiblePerson": "Jorj Mike",
  "name": "Human1 Resources.",
  "phoneNumber": "7900 00 00 00",
  "email": "a@mail.ru"
}

//create department
POST http://127.0.0.1:8080/gdpr-expert-web/api/department/create HTTP/1.1
Content-Type: application/json

{
  "organisationId": 1,
  "responsiblePerson": "Jorj Mike",
  "name": "Human Resources.",
  "phoneNumber": "7900 00 00 00",
  "email": "a@mail.ru"
}

//delete organisation
DELETE http://127.0.0.1:8080/gdpr-expert-web/api/organisation/delete/7 HTTP/1.1

//update organisation
PUT http://127.0.0.1:8080/gdpr-expert-web/api/organisation HTTP/1.1
Content-Type: application/json

{
  "id": 11,
  "organisationName": "12abc",
  "address": "str. cde",
  "email": "2@mail.ru",
  "telephone": "+373 134 13413 134",
  "legalRepresentative": "Jorik",
  "description": "Best organisation.",
  "base64LogoImage": "",
  "legalForm": "Cooperativă de producție",
  "foundedAt": "2000-11-22"
}

//create organisation
POST http://127.0.0.1:8080/gdpr-expert-web/api/organisation/create HTTP/1.1
Content-Type: application/json

{
  "organisationName": "12abc",
  "address": "str. cde",
  "email": "2@mail.ru",
  "telephone": "+373 134 13413 134",
  "legalRepresentative": "Jorik",
  "description": "Best organisation.",
  "base64LogoImage": "Hello world",
  "legalForm": "Cooperativă de producție",
  "foundedAt": "2000-11-22"
}

POST http://127.0.0.1:8080/gdpr-expert-web/api/auth/a HTTP/1.1

GET http://127.0.0.1:8080/gdpr-expert-web/api/auth/failure HTTP/1.1

GET http://127.0.0.1:8080/gdpr-expert-web/api/auth/success HTTP/1.1

